### ISSUE TITLE
Bug in CICIDS notebook

### ISSUE THREAD

**Issue by ISorokos** [ISorokos/SafeML#9]
In [4], in the train_model_predict method, the loop iterating over the stratified kfold needs to include the model fit and aggregate the predicted results as well.

Similar issue happens in method get_shuffled_stratifiedKFold_train_test_split, its results need to be concatenated over all the iterations.

**Comment by WillBridges1999** [comment]
Very true. I took it out originally as it took too long to run and didn't provide any meaningful benefits to the overall results (especially since 100 permutations are run anyway). I was going to rename the methods and just use simple splitting but I kept some of the code in case one wanted to implement it later. So, it can be renamed and slightly refactored or the actual K-Folds can be run (the stratification still occurs, just no K-Folds are run); what would be the ideal choice?

**Comment by ISorokos** [comment]
Thanks for the clarification. I would opt for using actual K-fold then.
@HarithF opinion ?

**Comment by HarithF** [comment]
I agree, opting K-folds would be a better idea. Since @WillBridges1999 seems to have tested and confirmed that the original implementation didn't provide a meaningful contribution, then I don't see a point in putting time and effort in refactoring it.
